version: '3'

services:
  api:
    container_name: iluvcoffee-api
    tty: true
    volumes:
      - type: bind
        source: "./api"
        target: "/app"
    working_dir: '/app'
    ports:
      - "3000:3000"
    build: "./api"
    depends_on:
      - postgres
  postgres:
    container_name: iluvcoffee-db
    tty: true
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      TZ: "Asia/Tokyo"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres-init/init:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@nitakan.net # login email for pgadmin
      PGADMIN_DEFAULT_PASSWORD: password      # login password for pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  postgres:
  pgadmin: